### ISSUE TITLE
Vaadin 14 Grid no longer work in iOS 13.2

### ISSUE THREAD

**Issue by jreina2s** [vaadin/vaadin-grid#1672]
Vaadin Grid 14 is no longer scrolling

**Comment by tomivirkki** [comment]
This might have been already fixed by https://github.com/vaadin/vaadin-grid/pull/1671

Can you check if it works for you in https://cdn.vaadin.com/vaadin-grid/5.5.0/demo/#grid-basic-demos

**Comment by jreina2s** [comment]
it works, i think i need to update the vaadin version. Thank you.

**Comment by jreina2s** [comment]
It still not work in Vaadin 14.0.12

**Comment by tomivirkki** [comment]
The recently released Vaadin 14.0.13 should now be running the latest `vaadin-grid` version with this fix included

**Comment by jreina2s** [comment]
I updated the Vaadin version to 14.0.13 in my pom.xml and rebuild my project ... it´s still not scrolling on iPad.
Grid 5.4.12

**Comment by tomivirkki** [comment]
That's strange... The following demo is also running Grid 5.4.12 and it scrolls well (on iPad simulator at least): https://cdn.vaadin.com/vaadin-grid/5.4.12/demo/#grid-basic-demos

**Comment by jreina2s** [comment]
Well my app uses the Version 5.5.0 from the Vaadin 14.1.0.beta1 wich i used before.
(i´ve checked it with the chrome console but I do not know how to check it on the iPad)
